// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ShelfScout.Api;

#nullable disable

namespace ShelfScout.Api.Migrations
{
    [DbContext(typeof(ShelfScoutDbContext))]
    [Migration("20260705233709_AddConsumptionStat")]
    partial class AddConsumptionStat
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ShelfScout.Api.Domain.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("HouseholdId")
                        .HasColumnType("integer")
                        .HasColumnName("household_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_categories");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_categories_name")
                        .HasFilter("household_id IS NULL");

                    b.HasIndex("HouseholdId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_categories_household_id_name")
                        .HasFilter("household_id IS NOT NULL");

                    b.ToTable("categories", (string)null);
                });

            modelBuilder.Entity("ShelfScout.Api.Domain.ConsumptionStat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("CategoryIsGlobal")
                        .HasColumnType("boolean")
                        .HasColumnName("category_is_global");

                    b.Property<string>("CategoryLabel")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("category_label");

                    b.Property<int>("Count")
                        .HasColumnType("integer")
                        .HasColumnName("count");

                    b.Property<int>("HouseholdId")
                        .HasColumnType("integer")
                        .HasColumnName("household_id");

                    b.Property<string>("LocationKind")
                        .HasColumnType("text")
                        .HasColumnName("location_kind");

                    b.Property<DateOnly>("PeriodMonth")
                        .HasColumnType("date")
                        .HasColumnName("period_month");

                    b.Property<string>("RemovalReason")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("removal_reason");

                    b.HasKey("Id")
                        .HasName("pk_consumption_stats");

                    b.HasIndex("HouseholdId", "PeriodMonth", "LocationKind", "RemovalReason", "CategoryLabel", "CategoryIsGlobal")
                        .IsUnique()
                        .HasDatabaseName("ix_consumption_stats_household_id_period_month_location_kind_r");

                    b.ToTable("consumption_stats", (string)null);
                });

            modelBuilder.Entity("ShelfScout.Api.Domain.Household", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("DefaultAlertThresholdDays")
                        .HasColumnType("integer")
                        .HasColumnName("default_alert_threshold_days");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_households");

                    b.ToTable("households", (string)null);
                });

            modelBuilder.Entity("ShelfScout.Api.Domain.Identity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("provider");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("subject");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_identities");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_identities_user_id");

                    b.HasIndex("Provider", "Subject")
                        .IsUnique()
                        .HasDatabaseName("ix_identities_provider_subject");

                    b.ToTable("identities", (string)null);
                });

            modelBuilder.Entity("ShelfScout.Api.Domain.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CategoryId")
                        .HasColumnType("integer")
                        .HasColumnName("category_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("integer")
                        .HasColumnName("created_by");

                    b.Property<DateOnly>("ExpiryDate")
                        .HasColumnType("date")
                        .HasColumnName("expiry_date");

                    b.Property<int>("HouseholdId")
                        .HasColumnType("integer")
                        .HasColumnName("household_id");

                    b.Property<int>("LocationId")
                        .HasColumnType("integer")
                        .HasColumnName("location_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("RemovalReason")
                        .HasColumnType("text")
                        .HasColumnName("removal_reason");

                    b.Property<DateTimeOffset?>("RemovedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("removed_at");

                    b.HasKey("Id")
                        .HasName("pk_items");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("ix_items_category_id");

                    b.HasIndex("HouseholdId")
                        .HasDatabaseName("ix_items_household_id");

                    b.HasIndex("LocationId")
                        .HasDatabaseName("ix_items_location_id");

                    b.ToTable("items", (string)null);
                });

            modelBuilder.Entity("ShelfScout.Api.Domain.Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AlertThresholdDays")
                        .HasColumnType("integer")
                        .HasColumnName("alert_threshold_days");

                    b.Property<int>("HouseholdId")
                        .HasColumnType("integer")
                        .HasColumnName("household_id");

                    b.Property<string>("Kind")
                        .HasColumnType("text")
                        .HasColumnName("kind");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_locations");

                    b.HasIndex("HouseholdId")
                        .HasDatabaseName("ix_locations_household_id");

                    b.ToTable("locations", (string)null);
                });

            modelBuilder.Entity("ShelfScout.Api.Domain.Membership", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.Property<int>("HouseholdId")
                        .HasColumnType("integer")
                        .HasColumnName("household_id");

                    b.Property<DateTimeOffset>("JoinedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("joined_at");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.HasKey("UserId", "HouseholdId")
                        .HasName("pk_memberships");

                    b.HasIndex("HouseholdId")
                        .HasDatabaseName("ix_memberships_household_id");

                    b.ToTable("memberships", (string)null);
                });

            modelBuilder.Entity("ShelfScout.Api.Domain.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("ShelfScout.Api.Domain.Category", b =>
                {
                    b.HasOne("ShelfScout.Api.Domain.Household", "Household")
                        .WithMany()
                        .HasForeignKey("HouseholdId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_categories_households_household_id");

                    b.Navigation("Household");
                });

            modelBuilder.Entity("ShelfScout.Api.Domain.ConsumptionStat", b =>
                {
                    b.HasOne("ShelfScout.Api.Domain.Household", "Household")
                        .WithMany()
                        .HasForeignKey("HouseholdId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_consumption_stats_households_household_id");

                    b.Navigation("Household");
                });

            modelBuilder.Entity("ShelfScout.Api.Domain.Identity", b =>
                {
                    b.HasOne("ShelfScout.Api.Domain.User", "User")
                        .WithMany("Identities")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_identities_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ShelfScout.Api.Domain.Item", b =>
                {
                    b.HasOne("ShelfScout.Api.Domain.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_items_categories_category_id");

                    b.HasOne("ShelfScout.Api.Domain.Household", "Household")
                        .WithMany("Items")
                        .HasForeignKey("HouseholdId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_items_households_household_id");

                    b.HasOne("ShelfScout.Api.Domain.Location", "Location")
                        .WithMany("Items")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_items_locations_location_id");

                    b.Navigation("Category");

                    b.Navigation("Household");

                    b.Navigation("Location");
                });

            modelBuilder.Entity("ShelfScout.Api.Domain.Location", b =>
                {
                    b.HasOne("ShelfScout.Api.Domain.Household", "Household")
                        .WithMany("Locations")
                        .HasForeignKey("HouseholdId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_locations_households_household_id");

                    b.Navigation("Household");
                });

            modelBuilder.Entity("ShelfScout.Api.Domain.Membership", b =>
                {
                    b.HasOne("ShelfScout.Api.Domain.Household", "Household")
                        .WithMany("Memberships")
                        .HasForeignKey("HouseholdId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_memberships_households_household_id");

                    b.HasOne("ShelfScout.Api.Domain.User", "User")
                        .WithMany("Memberships")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_memberships_users_user_id");

                    b.Navigation("Household");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ShelfScout.Api.Domain.Household", b =>
                {
                    b.Navigation("Items");

                    b.Navigation("Locations");

                    b.Navigation("Memberships");
                });

            modelBuilder.Entity("ShelfScout.Api.Domain.Location", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("ShelfScout.Api.Domain.User", b =>
                {
                    b.Navigation("Identities");

                    b.Navigation("Memberships");
                });
#pragma warning restore 612, 618
        }
    }
}
